### ISSUE TITLE
ses.UnsafeError should not be accessible

### ISSUE THREAD

**Issue by kpreid** [google/caja#1516]
Original [issue 1516](https://code.google.com/p/google-caja/issues/detail?id=1516) created by justinlpombrio on 2012-08-31T17:36:06.000Z:

<b>What steps will reproduce the problem?</b>

1. Initialize Ses
2. Evaluate Ses.UnsafeError

<b>What is the expected output? What do you see instead?</b>

You get a reference to the _unfrozen_ Error primordial. This should not be accessible after Ses has initialized.

Quoth Mark Miller, &quot;That's a good point about ses.UnsafeError. Really, that shouldn't be accessible after initialization even to SES privileged code. Please file this as a bug, though not a security hole.&quot;

**Comment by erights** [comment]
https://codereview.appspot.com/226970043/

**Comment by erights** [comment]
Does anyone mind if we reverse this and make UnsafeError available again to privileged code via
ses.UnsafeError
as it was?
