### ISSUE TITLE
Deal with Object.observe()

### ISSUE THREAD

**Issue by kpreid** [google/caja#1934]
Original [issue 1936](https://code.google.com/p/google-caja/issues/detail?id=1936) created by kpreid@google.com on 2014-09-08T17:26:56.000Z:

Object.observe is present in Chrome 36. Object.observe can break the WeakMap emulation. WeakMap has also been enabled in the same version, so the emulation will not be used in this case.

However, WeakMap.js should, for correctness, do one of: 
1. patching Object.observe to suppress the hidden name,
2. deleting Object.observe, or
3. refusing to run.

For plain SES/Caja sandboxing, even if we had observe but not WeakMap, there would be no effects because Object.observe is not on the SES whitelist.

There would be a problem if innocent code was using Object.observe on objects given to it by guest code, and passing information about keys back, but that is already a potential problem since the host frame isn't patched to hide the hidden property.

**Comment by jasvir** [comment]
Given the now public withdrawal of Object.observe (https://mail.mozilla.org/pipermail/es-discuss/2015-November/044684.html) I think we can close this issue as obsolete.

**Comment by erights** [comment]
@jasvir yes, this issue is now obsolete.
