### ISSUE TITLE
Cross-frame for-in is broken on Firefox 37, 38 beta

### ISSUE THREAD

**Issue by kpreid** [google/caja#1960]
Original [issue 1962](https://code.google.com/p/google-caja/issues/detail?id=1962) created by kpreid@google.com on 2015-04-06T23:26:43.000Z:

Firefox 37 and 38.0 beta.

  var o = frame.untame(frame.iframe.contentWindow.eval('({})'));
  for (var x in o) {}

The for loop throws &quot;TypeError: undefined is not a function&quot;. This shouldn't even be possible (without proxies, and there aren't any proxies here), so it's probably a browser bug.

Any untame()d record object exhibits the problem. The unsafe eval is just to have less machinery involved.

Other language meta-operations (e.g. getOwnPropertyNames) on the object work normally.

**Comment by erights** [comment]
https://codereview.appspot.com/222570043/
