### ISSUE TITLE
Firefox 40 Nightly moved the error.stack property where debug.js was not finding it

### ISSUE THREAD

**Issue by kpreid** [google/caja#1962]
Original [issue 1964](https://code.google.com/p/google-caja/issues/detail?id=1964) created by erights on 2015-04-12T00:39:41.000Z:

On Firefox 40 Nightly, the .stack property on error objects is now a not-so-magical accessor property inherited from Error.prototype. Of course, Error.prototype.stack is not on our whitelist so it was deleted. This results in debug.js (and thus useHTMLLogger.js) presenting FF40 Nightly as a platform without accessible error stacks.

**Comment by erights** [comment]
https://codereview.appspot.com/226970043/
