### ISSUE TITLE
Whitelist the "optimum" attribute for <meter>

### ISSUE THREAD

**Issue by douyo** [google/caja#1969]
It doesn't look like the `optimum` attribute for [`<meter>`](https://html.spec.whatwg.org/multipage/forms.html#the-meter-element) is whitelisted

**Comment by kpreid** [comment]
https://codereview.appspot.com/255390043/

**Comment by kpreid** [comment]
Fixed in 11b8172d20d029d6f20dc0786539fc08d4c5995f. Looks like it was just forgotten!
