### ISSUE TITLE
Missing top level README

### ISSUE THREAD

**Issue by erights** [google/caja#1973]
I notice that https://github.com/google/caja does have a home page. Should this have been automatically converted to a top-level README by the code.google -> github conversion tool?

**Comment by kpreid** [comment]
There's no automated conversion. But you're right, we _should_ have a README. Unfortunately, lots of the intro text we have is semi-obsolete ("The Caja Compiler..." — we're not any sort of compiler any more.)

**Comment by jasvir** [comment]
I know that the text there isn't entirely accurate but I just created a PR for https://github.com/google/caja/pull/1987 - lets get something up and we can correct it rather than having nothing at all.
