### ISSUE TITLE
SES not supported, aborting taming frame initialization in Chrome 45

### ISSUE THREAD

**Issue by kurttomlinson** [google/caja#1979]
How to reproduce:
1) Navigate to https://developers.google.com/caja/demos/gettingstarted/host.html
2) Expected result:

> Caja host page
> Static hello world
> Dynamic hello world

3) Actual result:
> Caja host page

Browser: Chrome Version 45.0.2454.85 m
OS: Windows 7 Pro x64

Error:
![image](https://cloud.githubusercontent.com/assets/1914753/9769513/480908a0-56f0-11e5-81e6-4cee6c71d1fa.png)

**Comment by kpreid** [comment]
Needed to update the version deployed on caja.appspot.com. Done. Thanks for the report.

**Comment by kurttomlinson** [comment]
Thanks!
