### ISSUE TITLE
Closure compiler type errors in sanitizer

### ISSUE THREAD

**Issue by mikesamuel** [google/caja#1982]
John Lenz reported

"""
I would like to get these warning fixed:

.../html-sanitizer-bundle.js:2078: ERROR - restricted index type
found   : string
required: number
          attribs = decision['attribs'];
                             ^

.../html-sanitizer-bundle.js:2085: ERROR - restricted index type
found   : string
required: number
          tagNameRep = decision['tagName'];
"""

**Comment by kpreid** [comment]
Pushed as 27248d0f223038346d63278b52ec038e77418ba9
