### ISSUE TITLE
caja playground seems to be completely broken now

### ISSUE THREAD

**Issue by oresmus** [google/caja#1984]
I have never tried the caja playground before. Trying it now (navigating firefox on mac to http://caja.appspot.com/, then clicking on the "canvas clock" example on the left), I just get three server error messages (two immediately, then the third after a half second or so), like this:

![screen shot 2015-09-27 at 1 08 56 pm](https://cloud.githubusercontent.com/assets/13971761/10124983/5d393a6a-6519-11e5-9176-831d768613c6.png)

This has happened several times in a row. It also happens in Safari.

**Comment by Stephn-R** [comment]
Agreed, I am getting the same issues even using the examples on the left

**Comment by kpreid** [comment]
This problem appears to be some Java 8 (class file major version = 52) classes getting into the playground build. Currently searching for the exact culprits.

**Comment by kpreid** [comment]
It's the playground sources itself not being targeted to 1.7.

**Comment by kpreid** [comment]
Fixed by commit 95463c09b46a9ac78a1171d810bfd5e2bf5476cc.
