### ISSUE TITLE
Instructions for setting up a caja server

### ISSUE THREAD

**Issue by Lyla-Fischer** [google/caja#1988]
I'm currently looking to see if it might be possible to integrate the services provided by Caja into a project that I am working on that will allow instructors and course authors (who are not professional, trusted developers) to provide client-side code that will be used as part of an online learning experience. I'm using the [XBlock API](https://github.com/edx/XBlock) in a [client-side-authoring XBlock](https://github.com/Lyla-Fischer/client_side_authoring) into which I am hoping to integrate Caja. 

Unfortunately, the API that Caja currently provides does not integrate well with this particular XBlock because Caja currently assumes that the client-side code of interest is being hosted on an external website (like an iframe) rather than being served as an untrusted component of a webpage as it is being rendered. I would like to see if I can harvest the guts of Caja in a way that will allow this XBlock to continue to receive updates as Caja matures, but I can only do that if I know how to mess with Caja code and run it locally. Halp?

(As an aside, another feature of interest would be to cache cajoled versions of client-provided client-side code, but I'm mentioning it only as a point of interest rather than the main question.)

**Comment by kpreid** [comment]
When creating the Caja guest "frame", you can specify the HTML or JS content to load directly (as a string) rather than fetching it from any URL.

Please use https://groups.google.com/forum/#!forum/google-caja-discuss for further questions rather than this issue tracker.

**Comment by Lyla-Fischer** [comment]
Thanks.
