### ISSUE TITLE
Throwing errors in console about depreciation

### ISSUE THREAD

**Issue by joeybab3** [google/caja#1992]
Look I'm not sure what this is exactly, but it's loading on my page(It appears to be part of base.js from youtube?), and it's throwing this error:
SVG's SMIL animations (< animate >, < set >, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.

**Comment by kpreid** [comment]
I just took a look and I can see the message you're talking about, but it appears to be in YouTube-specific code, not anything from Caja, so there's nothing for us to do here. Sorry!
