### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by LukasBombach** [google/caja#2000]
Hi there, we can really make use of this project (or something similar) at welt.de one of Germany's biggest daily newspapers. However it seems this project isn't really active anymore. So imma just ask naively: Is this project abandoned? Can it still be used?

**Comment by kpreid** [comment]
In the future, please use google-caja-discuss@googlegroups.com for questions, not the issue tracker.

New features are pretty much on hold, but a few of us are making sure it keeps running.

I have some plans for refactoring and removal of legacy code that will make it easier to make further progress, but it's still going to be a while before that can happen.

**Comment by LukasBombach** [comment]
I'll join the mailinglist, thanks.

**Comment by erights** [comment]
Several of us, including myself, are [working towards](https://github.com/FUDCo/proposal-frozen-realms) extracting lower layers of the SES implementation into separate ECMAScript proposals, to be separately shimmed. Given either shim or platform implementation of these proposals, we hope it will be trivial to rebuild SES on top of these lower layers mechanisms. In the process, we expect to update SES to track ES2015 and later standards.
