### ISSUE TITLE
ses.funcLike fails on bound functions on Chrome

### ISSUE THREAD

**Issue by kpreid** [google/caja#2001]
ses.funcLike(function() {}, function x() {}.bind(null))
    ⇒ SyntaxError: Unexpected identifier

Works on Firefox, fails on Chrome 50.0.2661.102

**Comment by erights** [comment]
What's happening is that makeStandinMaker is generating and evaling the following string, presumably because the name of 
```js
function x() {}.bind(null)
```
on Chrome 50 is "bound x". Will fix.


```js
(function makeStandin(newF) {
  "use strict";
  return function bound x() {
    return newF.apply(this, arguments);
  }
})
```

**Comment by erights** [comment]
The change needed is that the line at https://github.com/google/caja/blob/master/src/com/google/caja/ses/repairES5.js#L1133 which is currently

```js
if (!/[a-zA-Z][a-zA-Z0-9]*/.test(standinName)) {
```

should instead be

```js
if (!/^[a-zA-Z][a-zA-Z0-9]*$/.test(standinName)) {
```

IOW, the test for checking that it is an identifier was already there, but I forgot to anchor the ends of the regexp.

Kevin, I'm still traveling. Could you take it from here and I'll review? Thanks.
