### ISSUE TITLE
API documentation link is dead

### ISSUE THREAD

**Issue by phiros** [google/caja#2008]
I just visited https://developers.google.com/caja/ and noticed that the link to the API documentation is broken.

**Comment by erights** [comment]
Do you mean https://developers.google.com/caja/docs/gettingstarted/
Please try again and let us know if it still seems broken for you.

(FWIW, does not seem broken for me. See also https://validator.w3.org/checklink?uri=https%3A%2F%2Fdevelopers.google.com%2Fcaja%2F&hide_type=all&depth=&check=Check#results1 )

**Comment by kurttomlinson** [comment]
The API documentation link is broken for me too. It's the link titled "API Reference" in the left sidebar on the Google Caja homepage (https://developers.google.com/caja/)

Broken API documentation link: http://google-caja.googlecode.com/svn/doc/cajajs/index.html

**Comment by erights** [comment]
Thanks. Yes, it is broken for me too.

@kpreid Is there a corresponding page on the github site we could link to?

**Comment by kpreid** [comment]
That's funny. By the URL I would assume that it's pointing directly into the repository, but https://github.com/google/caja/tree/master/doc/cajajs does not have a `.html` file checked in. (`cajajs.xml` is the source from which it was built, I believe.)

We can rebuild that file but I'm not sure how the old URL worked.

**Comment by Sventenhaaf** [comment]
Any updates on this? An alternative URL maybe? Thanks!

**Comment by TomBaxter** [comment]
Where can I find the Caja API reference? Not the getting started, but the full Doc.

Thanks!

**Comment by Marchhill** [comment]
@TomBaxter not ideal but for now maybe you could use the wayback machine [here](https://web.archive.org/web/20160418083006/http://google-caja.googlecode.com/svn/doc/cajajs/index.html)?
@kpreid any progress in building this?

**Comment by Cypher1** [comment]
Any update on this? I'm hoping to use Caja for a project but am hoping to avoid reading too much of the source to do so.

**Comment by kpreid** [comment]
Links on https://developers.google.com/caja/ fixed.
