### ISSUE TITLE
"show in folder" in chrome/chomium downloads just opens folder in caja, but does not selects particular file

### ISSUE THREAD

**Issue by unxed** [google/caja#2009]

**Comment by kpreid** [comment]
Sorry, can you explain further how Caja is involved? Download behavior is generally dependent on the server's HTTP responses which Caja doesn't affect.

**Comment by unxed** [comment]
sorry for this, it's actually issue of MATE's caja, closing.

**Comment by kpreid** [comment]
No problem; thanks for following up.
