### ISSUE TITLE
Content of iframe's not loading

### ISSUE THREAD

**Issue by bkostrowiecki** [google/caja#2012]
Hi there,

I have been trying to use Caja. I cannot force it to load the content of iframes.
Example code for a playground:
```
<iframe width="560" height="315" src="https://www.youtube.com/embed/o4jgPdGrZYI" frameborder="0" allowfullscreen></iframe>
```
It's seems like Caja doesn't load the iframe content even when URL of the resource does not violate the URI policy.

Docs are not too friendly, so maybe I am missing something.

I found the issue which suggest to turn off the iframe's content loading by default because of security reasons, but it is labeled as started so I think it is propably not finished yet.

**Comment by kpreid** [comment]
We don't support loading `iframe src=` content. I did look into doing that, but it's nowhere near adequately implemented.

Also, if it were possible, iframe content would still be subject to Caja's security policies and virtualization. While I haven't looked in detail, It's likely that something as complex and not-built-for-Caja as a video player embed will not work within Caja.
