### ISSUE TITLE
Caja does not make use of SMB2 FSCTL_SRV_COPYCHUNK

### ISSUE THREAD

**Issue by godfuture** [google/caja#2034]
Copying or moving files within a share that holds two mounts of different devices sends the data to client and client has to send it back to server. 

FSCTL_SRV_COPYCHUNK should avoid the indirection to client and directly move it from one device to the other on server.

Tested on Ubuntu Mate 18.04 with Caja 1.20.2. Server has samba 4.1+ installed.

**Comment by kpreid** [comment]
I'm sorry, but you've found the wrong project named Caja. This project is about JavaScript sandboxing and has nothing to do with the desktop file manager.
