### ISSUE TITLE
null pointer error

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/caja#2035]
child  may be null

https://github.com/google/caja/blob/43ee1c8f4f6d44032173d1c1da2d04b96f81ecf6/src/com/google/caja/parser/AbstractParseTreeNode.java#L330-L343

**Comment by kpreid** [comment]
Can you provide a reproduction case demonstrating a NullPointerException?

**Comment by QiAnXinCodeSafe** [comment]
I'm sorry for my mistake
