### ISSUE TITLE
[debug.js] TODO(erights): "Explore alternatives to using "instanceof Error"

### ISSUE THREAD

**Issue by serapath** [google/caja#2040]
> https://github.com/google/caja/blob/master/src/com/google/caja/ses/debug.js
>  * <p>TODO(erights): Explore alternatives to using "instanceof Error"
>  * within this file.  Using "instanceof" makes this fail when used
>  * inter-realm. In ES6 no good inter-realm brand check seems
>  * possible. But even intra-realm, "instanceof" is not a brand check
>  * so there would be no loss of integrity in switching to some other
>  * heuristic.

Just came across this comment and in case it's still an open **todo**, I think you might be able to use:
* `(new Error()).constructor.name === "Error")`

It's not bullet proof and not a big deal, but then again neither is `instanceof`, e.g.:
```js
var e = new Error()
e.__proto__ = null
console.log(e instanceof Error) // => false
```

**Comment by pyrocto** [comment]
On Chrome, Safari, and Firefox, `({}).toString.call(new Error())` returns `[object Error]`.
